spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: false
    open-in-view: false

innospots:
  data:
    schemaCacheTimeoutSecond: 30
    recordStoreType: mysql
  db:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    jdbc-url: jdbc:mysql://${DB_IP}:${DB_PORT:3306}/${DB_NAME}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=${DB_TIMEZONE:GMT%2B8}&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximum-pool-size: 64
    minimum-idle: 4
    pool-name: innospots-pool
    max-lifetime: 1800000
    idle-timeout: 600000 # millisecond,default ten minute

  workflow:
    executionStorePath: .execution_contexts
    server:
      port: ${innosports.workflow.server.port:19876}